//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADC.Portal.Persistencia.Repositorio.Mensagem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificacoesMsg_Br {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificacoesMsg_Br() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADC.Portal.Persistencia.Repositorio.Mensagem.NotificacoesMsg_Br", typeof(NotificacoesMsg_Br).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou senha inválida.
        /// </summary>
        internal static string LoginOuSenhaInvalida {
            get {
                return ResourceManager.GetString("LoginOuSenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não é único.
        /// </summary>
        internal static string NaoEhUnico {
            get {
                return ResourceManager.GetString("NaoEhUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado.
        /// </summary>
        internal static string NaoEncontrado {
            get {
                return ResourceManager.GetString("NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros não encontrados.
        /// </summary>
        internal static string NaoEncontrados {
            get {
                return ResourceManager.GetString("NaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não é único(a).
        /// </summary>
        internal static string XNaoEhUnico {
            get {
                return ResourceManager.GetString("XNaoEhUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrado(a).
        /// </summary>
        internal static string XNaoEncontrado {
            get {
                return ResourceManager.GetString("XNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrados(as).
        /// </summary>
        internal static string XNaoEncontrados {
            get {
                return ResourceManager.GetString("XNaoEncontrados", resourceCulture);
            }
        }
    }
}
